mutation UpdatePasswordMutation(
	$current_password: String!
	$password: String!
	$password_confirmation: String!
) {
	update_password(
		current_password: $current_password
		password: $password
		password_confirmation: $password_confirmation
	) {
		id
		updated_at
	}
}
