query Exam($search_text: String, $size: Int) {
	userSessions(search_text: $search_text, size: $size) {
		exams {
			id
			name
			exam_questions_count
			exam_sessions {
				id
				responses_count
			}
			author {
				name
			}
			job {
				name
			}
			organization {
				name
			}
		}
	}
}
