image: "elixir:1.9"

.cache_deps: &cache_deps
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - deps
      - assets/node_modules

cache:
  paths:
    - deps
    - assets/node_modules

test:
  <<: *cache_deps
  stage: test
  services:
    - redis:latest
    - postgres:latest
  variables:
    POSTGRES_DB: hello_gitlab_ci_test
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"
    MIX_ENV: "test"
    REDIS_URL: redis://redis:6379/12
  script:
    # Install locale
    # in case of strange errors
    # - apt-get install -y locales >/dev/null
    # - echo "en_US UTF-8" > /etc/locale.gen
    # - locale-gen en_US.UTF-8
    # - export LANG=en_US.UTF-8
    # - export LANGUAGE=en_US:en
    # - export LC_ALL=en_US.UTF-8
    - apt-get update && apt-get -y install postgresql-client
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only test
    - mix ecto.create
    - mix ecto.load
    - mix coveralls.json
    - bash <(curl -s https://codecov.io/bash)

staging:
  image: "ruby:2.6.2"
  stage: deploy
  environment:
    name: staging
  script:
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGING_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - develop
    - staging

production:
  image: "ruby:2.6.2"
  stage: deploy
  environment:
    name: production
  script:
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master
