coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto 
        if_not_found: success
        if_ci_failed: error